# Generated by Django 2.1.5 on 2019-02-24 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0003_auto_20190224_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identificativo del medico', primary_key=True, serialize=False),
        ),
    ]
