# Generated by Django 2.1.5 on 2019-02-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0004_auto_20190224_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['Last_Name', 'Name']},
        ),
    ]
