# Generated by Django 2.1.5 on 2019-02-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0005_auto_20190224_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Sesso',
            field=models.CharField(blank=True, choices=[('m', 'Maschio'), ('f', 'femmina')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
