# Generated by Django 2.1.5 on 2019-02-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0006_doctor_sesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Sesso',
            field=models.CharField(blank=True, choices=[('m', 'Maschio'), ('f', 'Femmina')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
