# Generated by Django 2.1.5 on 2019-02-24 17:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0008_auto_20190224_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='societa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='id società sportiva', primary_key=True, serialize=False)),
                ('Name', models.CharField(help_text='Nome Società.', max_length=100, null=True, verbose_name='Nome Società')),
                ('Piazza_Via_Corso', models.CharField(blank=True, choices=[('vi', 'Via'), ('va', 'Viale'), ('co', 'Corso'), ('pi', 'Piazza'), ('la', 'Largo'), ('al', 'Altro (specificare sotto)')], default='vi', max_length=2)),
                ('Città', models.CharField(max_length=50, null=True, verbose_name='Città')),
                ('Numero_Civico', models.CharField(max_length=10, null=True, verbose_name='N° Civico')),
                ('Provincia', models.CharField(blank=True, choices=[('AG', 'AGRIGENTO'), ('AN', 'ANCONA'), ('AO', 'AOSTA'), ('AQ', "L'AQUILA"), ('AG', 'Agrigento'), ('AR', 'AREZZO'), ('AP', 'ASCOLI-PICENO'), ('AT', 'ASTI'), ('AV', 'AVELLINO'), ('BA', 'BARI'), ('BT', 'BARLETTA'), ('BL', 'BELLUNO'), ('BN', 'BENEVENTO'), ('BG', 'BERGAMO'), ('BI', 'BIELLA'), ('BO', 'BOLOGNA'), ('BZ', 'BOLZANO'), ('BS', 'BRESCIA'), ('BR', 'BRINDISI'), ('CA', 'CAGLIARI'), ('CL', 'CALTANISETTA'), ('CB', 'CAMPOBASSO'), ('CI', 'CARBONIA IGLESIAS'), ('CE', 'CASERTA'), ('CT', 'CATANIA'), ('CZ', 'CATANZARO'), ('CH', 'CHIETI'), ('CO', 'COMO'), ('CS', 'COSENZA'), ('CR', 'CREMONA'), ('KR', 'CROTONE'), ('CN', 'CUNEO'), ('EN', 'ENNA'), ('FM', 'FERMO'), ('FE', 'FERRARA'), ('FI', 'FIRENZE'), ('FG', 'FOGGIA'), ('FC', 'FORLI-CESENA'), ('FR', 'FROSINONE'), ('GE', 'GENOVA'), ('GO', 'GORIZIA'), ('GR', 'GROSSETO'), ('IM', 'IMPERIA'), ('IS', 'ISERNIA'), ('SP', 'LA SPEZIA'), ('LT', 'LATINA'), ('LE', 'LECCE'), ('LC', 'LECCO'), ('LI', 'LIVORNO'), ('LO', 'LODI'), ('LU', 'LUCCA'), ('MC', 'MACERATA'), ('MN', 'MANTOVA'), ('MS', 'MASSA CARRARA'), ('MT', 'MATERA'), ('MI', 'MILANO'), ('MO', 'MODENA'), ('MB', 'MONZA BRIANZA'), ('NA', 'NAPOLI'), ('NO', 'NOVARA'), ('NU', 'NUORO'), ('OG', 'OGLIASTRA'), ('OT', 'OLBIA TEMPIO'), ('OR', 'ORISTANO'), ('PD', 'PADOVA'), ('PA', 'PALERMO'), ('PR', 'PARMA'), ('PV', 'PAVIA'), ('PG', 'PERUGIA'), ('PU', 'PESARO URBINO'), ('PE', 'PESCARA'), ('PC', 'PIACENZA'), ('PI', 'PISA'), ('PT', 'PISTOIA'), ('PN', 'PORDENONE'), ('PZ', 'POTENZA'), ('PO', 'PRATO'), ('RG', 'RAGUSA'), ('RA', 'RAVENNA'), ('RC', 'REGGIO CALABRIA'), ('RE', 'REGGIO EMILIA'), ('RI', 'RIETI'), ('RN', 'RIMINI'), ('ROMA', 'ROMA'), ('RO', 'ROVIGO'), ('SA', 'SALERNO'), ('SS', 'SASSARI'), ('SV', 'SAVONA'), ('SI', 'SIENA'), ('SR', 'SIRACUSA'), ('SO', 'SONDRIO'), ('TA', 'TARANTO'), ('TE', 'TERAMO'), ('TR', 'TERNI'), ('TO', 'TORINO'), ('TP', 'TRAPANI'), ('TN', 'TRENTO'), ('TV', 'TREVISO'), ('TS', 'TRIESTE'), ('UD', 'UDINE'), ('VA', 'VARESE'), ('VE', 'VENEZIA'), ('VB', 'VERBANIA'), ('VC', 'VERCELLI'), ('VR', 'VERONA'), ('VV', 'VIBO VALENTIA'), ('VI', 'VICENZA'), ('VT', 'VITERBO')], default='TO', help_text='Inserire la provincia operativa del medico', max_length=2)),
                ('tipologia', models.CharField(blank=True, choices=[('pa', 'Palestra'), ('ss', 'Società Sportiva'), ('pi', 'Piscina'), ('al', 'altro')], default='pa', max_length=2)),
                ('Email', models.EmailField(help_text='inserire un indirizzo mail valido.', max_length=90, null=True)),
                ('Email_secondaria', models.EmailField(blank=True, help_text='inserire un eventuale seconda Email.', max_length=90, null=True, verbose_name='Email Secondaria')),
                ('Numero_Telefonico', models.CharField(help_text='numero telefonico del medico', max_length=11, null=True)),
                ('Numero_Telefonico_Secondario', models.CharField(blank=True, help_text='Eventuale numero telefonico secondario', max_length=11, null=True, verbose_name='Numero telefonico secondario')),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Provincia',
            field=models.CharField(blank=True, choices=[('AG', 'AGRIGENTO'), ('AN', 'ANCONA'), ('AO', 'AOSTA'), ('AQ', "L'AQUILA"), ('AG', 'Agrigento'), ('AR', 'AREZZO'), ('AP', 'ASCOLI-PICENO'), ('AT', 'ASTI'), ('AV', 'AVELLINO'), ('BA', 'BARI'), ('BT', 'BARLETTA'), ('BL', 'BELLUNO'), ('BN', 'BENEVENTO'), ('BG', 'BERGAMO'), ('BI', 'BIELLA'), ('BO', 'BOLOGNA'), ('BZ', 'BOLZANO'), ('BS', 'BRESCIA'), ('BR', 'BRINDISI'), ('CA', 'CAGLIARI'), ('CL', 'CALTANISETTA'), ('CB', 'CAMPOBASSO'), ('CI', 'CARBONIA IGLESIAS'), ('CE', 'CASERTA'), ('CT', 'CATANIA'), ('CZ', 'CATANZARO'), ('CH', 'CHIETI'), ('CO', 'COMO'), ('CS', 'COSENZA'), ('CR', 'CREMONA'), ('KR', 'CROTONE'), ('CN', 'CUNEO'), ('EN', 'ENNA'), ('FM', 'FERMO'), ('FE', 'FERRARA'), ('FI', 'FIRENZE'), ('FG', 'FOGGIA'), ('FC', 'FORLI-CESENA'), ('FR', 'FROSINONE'), ('GE', 'GENOVA'), ('GO', 'GORIZIA'), ('GR', 'GROSSETO'), ('IM', 'IMPERIA'), ('IS', 'ISERNIA'), ('SP', 'LA SPEZIA'), ('LT', 'LATINA'), ('LE', 'LECCE'), ('LC', 'LECCO'), ('LI', 'LIVORNO'), ('LO', 'LODI'), ('LU', 'LUCCA'), ('MC', 'MACERATA'), ('MN', 'MANTOVA'), ('MS', 'MASSA CARRARA'), ('MT', 'MATERA'), ('MI', 'MILANO'), ('MO', 'MODENA'), ('MB', 'MONZA BRIANZA'), ('NA', 'NAPOLI'), ('NO', 'NOVARA'), ('NU', 'NUORO'), ('OG', 'OGLIASTRA'), ('OT', 'OLBIA TEMPIO'), ('OR', 'ORISTANO'), ('PD', 'PADOVA'), ('PA', 'PALERMO'), ('PR', 'PARMA'), ('PV', 'PAVIA'), ('PG', 'PERUGIA'), ('PU', 'PESARO URBINO'), ('PE', 'PESCARA'), ('PC', 'PIACENZA'), ('PI', 'PISA'), ('PT', 'PISTOIA'), ('PN', 'PORDENONE'), ('PZ', 'POTENZA'), ('PO', 'PRATO'), ('RG', 'RAGUSA'), ('RA', 'RAVENNA'), ('RC', 'REGGIO CALABRIA'), ('RE', 'REGGIO EMILIA'), ('RI', 'RIETI'), ('RN', 'RIMINI'), ('ROMA', 'ROMA'), ('RO', 'ROVIGO'), ('SA', 'SALERNO'), ('SS', 'SASSARI'), ('SV', 'SAVONA'), ('SI', 'SIENA'), ('SR', 'SIRACUSA'), ('SO', 'SONDRIO'), ('TA', 'TARANTO'), ('TE', 'TERAMO'), ('TR', 'TERNI'), ('TO', 'TORINO'), ('TP', 'TRAPANI'), ('TN', 'TRENTO'), ('TV', 'TREVISO'), ('TS', 'TRIESTE'), ('UD', 'UDINE'), ('VA', 'VARESE'), ('VE', 'VENEZIA'), ('VB', 'VERBANIA'), ('VC', 'VERCELLI'), ('VR', 'VERONA'), ('VV', 'VIBO VALENTIA'), ('VI', 'VICENZA'), ('VT', 'VITERBO')], default='TO', help_text='Inserire la provincia operativa del medico', max_length=2),
        ),
    ]
