# Generated by Django 2.1.5 on 2019-02-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0009_auto_20190224_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='societa',
            options={'ordering': ['Name']},
        ),
        migrations.AddField(
            model_name='societa',
            name='indirizzo',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome strada o via/corso'),
        ),
        migrations.AlterField(
            model_name='societa',
            name='Numero_Telefonico',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='societa',
            name='Piazza_Via_Corso',
            field=models.CharField(blank=True, choices=[('vi', 'Via'), ('va', 'Viale'), ('co', 'Corso'), ('pi', 'Piazza'), ('la', 'Largo'), ('st', 'Strada'), ('al', 'Altro (specificare sotto)')], default='vi', max_length=2),
        ),
    ]
