# Generated by Django 2.1.5 on 2019-02-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0011_visita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['data', 'ora_di_inizio', 'id']},
        ),
    ]
