# Generated by Django 2.1.5 on 2019-02-27 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0012_auto_20190225_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pianificazione_visite.Doctor'),
        ),
    ]
