# Generated by Django 2.1.5 on 2019-02-27 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0013_visita_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='societa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pianificazione_visite.societa'),
        ),
    ]
