# Generated by Django 2.1.5 on 2019-03-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0016_auto_20190304_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='ora_di_fine',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pianificazione_visite.Doctor'),
        ),
    ]
