# Generated by Django 2.1.5 on 2019-03-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0021_auto_20190304_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='ora_di_inizio',
            field=models.TimeField(choices=[('06:00:00', '06:00:00')], null=True),
        ),
    ]
