# Generated by Django 2.1.5 on 2019-03-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0023_auto_20190304_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='ora_di_fine',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='ora_di_inizio',
            field=models.TimeField(null=True),
        ),
    ]
