# Generated by Django 2.1.5 on 2019-03-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0024_auto_20190304_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societa',
            name='Piazza_Via_Corso',
            field=models.CharField(blank=True, choices=[('Via', 'Via'), ('Viale', 'Viale'), ('Corso', 'Corso'), ('Piazza', 'Piazza'), ('Largo', 'Largo'), ('Strada', 'Strada'), ('Altro', 'Altro (specificare sotto)')], default='vi', max_length=10),
        ),
    ]
