# Generated by Django 2.1.5 on 2019-03-08 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0027_auto_20190304_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='stazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Stazione',
                'verbose_name_plural': 'Stazioni',
                'ordering': ['Nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['Last_Name', 'Name'], 'verbose_name': 'Dottore', 'verbose_name_plural': 'Dottori'},
        ),
        migrations.AlterModelOptions(
            name='societa',
            options={'ordering': ['Name'], 'verbose_name': 'Società', 'verbose_name_plural': 'Società'},
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['data', 'ora_di_inizio', 'id'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visite'},
        ),
        migrations.AddField(
            model_name='visita',
            name='stazione',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pianificazione_visite.stazione'),
        ),
    ]
