# Generated by Django 2.1.5 on 2019-03-08 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0028_auto_20190308_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stazione',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
