# Generated by Django 2.1.5 on 2019-03-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0029_auto_20190308_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stazione',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
