# Generated by Django 2.1.5 on 2019-03-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0032_auto_20190308_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='attivo',
            field=models.BooleanField(default=True, help_text='Il medico lavora attualmente per noi?'),
        ),
        migrations.AddField(
            model_name='stazione',
            name='status',
            field=models.CharField(choices=[('Disponibile', 'Disponibile'), ('Manutenzione', 'Manutenzione'), ('Disattivata', 'Disattivata')], default='Disponibile', max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Email',
            field=models.EmailField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Email_secondaria',
            field=models.EmailField(blank=True, max_length=90, null=True, verbose_name='Email Secondaria'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Numero_Telefonico',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Numero_Telefonico_Secondario',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Numero telefonico secondario'),
        ),
    ]
