# Generated by Django 2.1.5 on 2019-03-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0033_auto_20190309_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'attivo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pianificazione_visite.Doctor'),
        ),
    ]
