# Generated by Django 2.1.5 on 2019-03-10 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0035_auto_20190309_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='societa',
            name='attiva',
            field=models.BooleanField(default=True, help_text='La società è nostra cliente attualmente?'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='societa',
            field=models.ForeignKey(limit_choices_to={'attiva': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pianificazione_visite.societa'),
        ),
    ]
