# Generated by Django 2.1.5 on 2019-03-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0036_auto_20190310_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='contatto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('cognome', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=90, null=True)),
                ('numero_telefonico', models.CharField(max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'Contatto',
                'verbose_name_plural': 'Contatti',
                'ordering': ['cognome', 'nome'],
            },
        ),
    ]
