# Generated by Django 2.1.5 on 2019-03-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0037_contatto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatto',
            name='societa',
            field=models.ForeignKey(limit_choices_to={'attiva': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='pianificazione_visite.societa'),
        ),
    ]
