# Generated by Django 2.1.5 on 2019-03-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0038_contatto_societa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatto',
            name='email',
            field=models.EmailField(blank=True, max_length=90, null=True),
        ),
    ]
