# Generated by Django 2.1.5 on 2019-03-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0039_auto_20190315_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatto',
            options={'ordering': ['cognome', 'nome'], 'permissions': (('can view HCT contacts', 'can view HCT contacts'), ('can view med+ contacts', 'can view med+ contacts'), ('can edit med+ contacts', 'can edit med+ contacts'), ('can edit HCT contacts', 'can edit HCT contacts'), ('can create HCT contacts', 'can create HCT contacts'), ('can create med+ contacts', 'can create med+ contacts')), 'verbose_name': 'Contatto', 'verbose_name_plural': 'Contatti'},
        ),
    ]
