# Generated by Django 2.1.5 on 2019-03-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0040_auto_20190315_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stazione',
            options={'ordering': ['Nome'], 'permissions': (('can view HCT stazione', 'can view HCT stazione'), ('can view med+ stazione', 'can view med+ stazione'), ('can edit med+ stazione', 'can edit med+ stazione'), ('can edit HCT stazione', 'can edit HCT stazione'), ('can create HCT stazione', 'can create HCT stazione'), ('can create med+ stazione', 'can create med+ stazione')), 'verbose_name': 'Stazione', 'verbose_name_plural': 'Stazioni'},
        ),
    ]
