# Generated by Django 2.1.5 on 2019-03-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0041_auto_20190315_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='societa',
            options={'ordering': ['Name'], 'permissions': (('can view HCT societa', 'can view HCT societa'), ('can view med+ societa', 'can view med+ societa'), ('can edit med+ societa', 'can edit med+ societa'), ('can edit HCT societa', 'can edit HCT societa'), ('can create HCT societa', 'can create HCT societa'), ('can create med+ societa', 'can create med+ societa')), 'verbose_name': 'Società', 'verbose_name_plural': 'Società'},
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['data', 'ora_di_inizio', 'id'], 'permissions': (('can view HCT visita', 'can view HCT visita'), ('can view med+ visita', 'can view med+ visita'), ('can edit med+ visita', 'can edit med+ visita'), ('can edit HCT visita', 'can edit HCT visita'), ('can create HCT visita', 'can create HCT visita'), ('can create med+ visita', 'can create med+ visita')), 'verbose_name': 'Visita', 'verbose_name_plural': 'Visite'},
        ),
    ]
