# Generated by Django 2.1.5 on 2019-03-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0043_auto_20190315_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='record_hct',
            field=models.BooleanField(default=False, help_text='Il medico lavora per HCT'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='record_med',
            field=models.BooleanField(default=False, help_text='Il medico lavora attualmente per Med+', verbose_name='Record Med+'),
        ),
    ]
