# Generated by Django 2.1.5 on 2019-03-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0044_auto_20190315_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatto',
            name='record_hct',
            field=models.BooleanField(default=False, help_text='Contatto di una Palestra HCT'),
        ),
        migrations.AddField(
            model_name='contatto',
            name='record_med',
            field=models.BooleanField(default=False, help_text='Contatto di una palestra Med+', verbose_name='Record Med+'),
        ),
        migrations.AddField(
            model_name='societa',
            name='record_hct',
            field=models.BooleanField(default=False, help_text='Palestra di HCT'),
        ),
        migrations.AddField(
            model_name='societa',
            name='record_med',
            field=models.BooleanField(default=False, help_text='Palestra di Med+', verbose_name='Record Med+'),
        ),
        migrations.AddField(
            model_name='stazione',
            name='record_hct',
            field=models.BooleanField(default=False, help_text='Stazione HCT'),
        ),
        migrations.AddField(
            model_name='stazione',
            name='record_med',
            field=models.BooleanField(default=False, help_text='Stazione Med+', verbose_name='Record Med+'),
        ),
        migrations.AddField(
            model_name='visita',
            name='record_hct',
            field=models.BooleanField(default=False, help_text='visita di HCT'),
        ),
        migrations.AddField(
            model_name='visita',
            name='record_med',
            field=models.BooleanField(default=False, help_text='Visita di Med+', verbose_name='Record Med+'),
        ),
    ]
