# Generated by Django 2.1.5 on 2019-03-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0046_auto_20190315_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatto',
            options={'ordering': ['cognome', 'nome'], 'verbose_name': 'Contatto', 'verbose_name_plural': 'Contatti'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['Last_Name', 'Name'], 'verbose_name': 'Dottore', 'verbose_name_plural': 'Dottori'},
        ),
        migrations.AlterModelOptions(
            name='societa',
            options={'ordering': ['Name'], 'verbose_name': 'Società', 'verbose_name_plural': 'Società'},
        ),
        migrations.AlterModelOptions(
            name='stazione',
            options={'ordering': ['Nome'], 'verbose_name': 'Stazione', 'verbose_name_plural': 'Stazioni'},
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['data', 'ora_di_inizio', 'id'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visite'},
        ),
        migrations.RemoveField(
            model_name='contatto',
            name='record_hct',
        ),
        migrations.RemoveField(
            model_name='contatto',
            name='record_med',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='record_hct',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='record_med',
        ),
        migrations.RemoveField(
            model_name='societa',
            name='record_hct',
        ),
        migrations.RemoveField(
            model_name='societa',
            name='record_med',
        ),
        migrations.RemoveField(
            model_name='stazione',
            name='record_hct',
        ),
        migrations.RemoveField(
            model_name='stazione',
            name='record_med',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='record_hct',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='record_med',
        ),
    ]
