# Generated by Django 2.1.5 on 2019-03-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0049_auto_20190316_1123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together=set(),
        ),
    ]
