# Generated by Django 2.1.5 on 2019-03-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0050_auto_20190316_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='lavorazione_visita',
            field=models.CharField(choices=[('Da_iniziare', 'Da Iniziare'), ('ECG_parziali', 'ECG Parzialmente inviati'), ('ECG_ricevuti', 'ECG ricevuti'), ('ECG_da_assegnare', 'ECG da assegnare'), ('ECG_assegnati', 'ECG assegnati'), ('ECG_parzialmente', 'ECG parzialmente refertati'), ('ECG_refertati', 'ECG refertati'), ('Visite_stampate', 'Visite stampate'), ('Visite_inviate', 'Visite Inviate'), ('Chiusa', 'Chiusa')], default='Da_iniziare', help_text='inserire la fase di lavorazione della sessione di visita', max_length=25),
        ),
        migrations.AlterField(
            model_name='visita',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'attivo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pianificazione_visite.Doctor', verbose_name='Medico assegnato'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='ora_di_fine',
            field=models.TimeField(help_text='inserire il dato in formato hh:mm:ss', null=True, verbose_name='Orario di fine'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='ora_di_inizio',
            field=models.TimeField(help_text='inserire in formato hh:mm:ss', null=True, verbose_name='Orario di inizio'),
        ),
    ]
