# Generated by Django 2.1.5 on 2019-03-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianificazione_visite', '0052_visita_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Provincia',
        ),
        migrations.RemoveField(
            model_name='societa',
            name='Provincia',
        ),
        migrations.AlterField(
            model_name='societa',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('pa', 'Palestra'), ('ss', 'Società Sportiva'), ('pi', 'Piscina'), ('al', 'altro')], default='pa', max_length=11),
        ),
    ]
